export const getAllProducts = () => {
  return [
    {
      id: "IOE-LUTAN-001",
      slug: "irides-of-eos-lukisan-metropolitan",
      name: "Irides of Eos",
      category: `Lukisan Metropolitan`,
      categorySlug: "lukisan-metropolitan",
      price: 11_000_000,
      stock: 3,
      imageUrl: "/assets/images/abstrak.jpg",
      description: `Berarti "Pelangi Eos," terinspirasi dari dewi fajar Yunani, menggambarkan warna-warna dinamis dan transisi lembut.`,
    },
    {
      id: "PS-LUKAM-002",
      slug: "pindos-serenity-lukisan-alam",
      name: "Pindos Serenity",
      category: `Lukisan Alam`,
      categorySlug: "lukisan-alam",
      price: 5_599_000,
      stock: 36,
      imageUrl: `/assets/images/mountain.jpg`,
      description: `Nama ini merujuk pada Pegunungan Pindos di Yunani, mencerminkan keindahan alam dan ketenangan pegunungan.`,
    },
    {
      id: "HG-LUKAM-003",
      slug: "hesperian-glow-lukisan-alam",
      name: "Hesperian Glow",
      category: `Lukisan Alam`,
      categorySlug: "lukisan-alam",
      price: 7_999_000,
      stock: 0,
      imageUrl: `/assets/images/sunset.jpg`,
      description: `Mengacu pada Hesperides, nimfa penjaga apel emas di ujung dunia yang sering dikaitkan dengan keindahan senja.`,
    },
    {
      id: "KS-LUTAN-004",
      slug: "kronos’-skyline-lukisan-metropolitan",
      name: "Kronos’ Skyline",
      category: `Lukisan Metropolitan`,
      categorySlug: "lukisan-metropolitan",
      price: 15_959_000,
      stock: 0,
      imageUrl: `/assets/images/cityy.jpg`,
      description: `Mengacu pada Kronos, dewa waktu, mencerminkan perkembangan kota sepanjang zaman dengan cakrawala yang megah.`,
    },
    {
      id: "NO-LUTAN-005",
      slug: "neon-olympus-lukisan-metropolitan",
      name: "Neon Olympus",
      category: `Lukisan Metropolitan`,
      categorySlug: "lukisan-metropolitan",
      price: 4_400_000,
      stock: 55,
      imageUrl: `/assets/images/cityy 2.jpg`,
      description: `Menggabungkan modernitas (neon) dengan kemegahan mitologis Gunung Olympus, sempurna untuk kota metropolitan.`,
    },
    {
      id: "MP-LUTAN-006",
      slug: "megali-polis-lukisan-metropolitan",
      name: "Megali Polis",
      category: `Lukisan Metropolitan`,
      categorySlug: "lukisan-metropolitan",
      price: 35_550_000,
      stock: 2,
      imageUrl: `/assets/images/maju.jpg`,
      description: `Lukisan ini menampilkan kota Yunani megah dan maju, dengan bangunan tinggi, jalan lebar, dan suasana sibuk.`,
    },
  ];
};
